language: generic
sudo: required
services: -docker

before_install:
  - docker build -t razasam007/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true razasam007/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: ''
  bucket_path: ''
  on:
    branch: master
