language: generic
sudo: required
services: -docker

before_install:
  - docker build -t razasam007/docker-react -f Doclerfile.dev .
script:
  - docker run -e CI=true razasam007/docker-react npm run test
